-- Supports the 4-round tournament flow: Round1 random groups, Round2 tier
-- round-robin, Round3/4 semifinal+final knockout per tier. `stage` distinguishes
-- matches generated by each round so regenerating one round doesn't clash with
-- matches from another (bracket_type/round alone aren't unique across rounds).
ALTER TABLE matches ADD COLUMN stage INTEGER NOT NULL DEFAULT 1;
